/*
 * FreeDockPanel.java
 *
 * Created on September 26, 2000, 1:11 PM
 */

package com.SoftWoehr.JaXWT;

/** A docking panel for FreePanel
 * @author jax
 * @version $Id: FreeDockPanel.java,v 1.2 2001-09-15 16:34:35 jwoehr Exp $
 */
public class FreeDockPanel extends javax.swing.JPanel {

  /** Creates new form FreeDockPanel */
  public FreeDockPanel() {
    initComponents ();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the FormEditor.
   */
  private void initComponents () {//GEN-BEGIN:initComponents
    setLayout (new java.awt.BorderLayout ());

  }//GEN-END:initComponents

  /** Extend this to call right at docking.
   * @param fp associated FreePanel
   */
  protected void hookBeforeDocking(FreePanel fp) {

  }

  /** Extend this to call right after docking.
   * @param fp associated FreePanel
   */
  protected void hookAfterDocking(FreePanel fp) {

  }

  /** Extend this to call right at undocking.
   * @param fp associated FreePanel
   */
  protected void hookBeforeUnDocking(FreePanel fp) {

  }

  /** Extend this to call right after undocking.
   * @param fp associated FreePanel
   */
  protected void hookAfterUnDocking(FreePanel fp) {

  }

  /** Add a FreePanel.
   * @param fp associated FreePanel
   */
  public void dock(FreePanel fp) {
    hookBeforeDocking(fp);
    add(fp);
    hookAfterDocking(fp);
  }

  /** Remove a FreePanel.
   * @param fp associated FreePanel
   */
  public void undock(FreePanel fp) {
    hookBeforeUnDocking(fp);
    remove(fp);
    hookAfterUnDocking(fp);
  }
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables

}