/*
 * FreePanel.java
 *
 * Copyright *C* 2001 Jack J. Woehr
 * All Rights Reserved
 * PO Box 51, Golden, Colorado 80402-0051 USA
 * http://www.softwoehr.com
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * Free Software NO WARRANTY NO GUARANTEE
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 *
 * Created on September 26, 2000, 1:15 PM
 */

package com.SoftWoehr.JaXWT;

/** A panel to dock into a FreeDockPanel
 * @see com.SoftWoehr.JaXWT.FreeDockPanel
 * @author  jax
 * @version $Id: FreePanel.java,v 1.1 2016-11-06 21:20:40 jwoehr Exp $
 */
public class FreePanel extends javax.swing.JPanel {

  /** Creates new form FreePanel */
  public FreePanel() {
    initComponents ();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the FormEditor.
   */
  private void initComponents () {//GEN-BEGIN:initComponents
    setLayout (new java.awt.BorderLayout ());

  }//GEN-END:initComponents

  /** Undock from current (or null) and dock into new (or null)
   * @param fdp associated free docking panel
   */
  public void dock (FreeDockPanel fdp) {
    if (null != getParent()) {
      ((FreeDockPanel)getParent()).undock(this);
    }
    if (null != fdp) {
      fdp.dock(this);
    }
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables

}